### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by MR-HOLO** [qinliuliuqin/iSegFormer#1]
Hello, can you send an oai-zib dataset

**Comment by MR-HOLO** [comment]
你好，我还有个问题，训练是没有问题的. iSegFormer得到的二维分割传播到3D图像中未分割的切片上，是如何进行的，具体操作。谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qinliuliuqin/iSegFormer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月14日(星期四) 晚上10:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qinliuliuqin/iSegFormer] datasets (Issue #1)

**Comment by qinliuliuqin** [comment]
你好，谢谢你的问题。Mask Prop 用的是STCN现有的模型，具体操作可参考: [https://github.com/qinliuliuqin/iSegFormer/blob/main/experiments/test_maskprop.ipynb](url). 
使用上面的代码，你需要下载:
1. STCN的模型: [https://github.com/hkchengrex/MiVOS/blob/MiVOS-STCN/download_model.py](url).
2. OAI-ZIB volume数据 (数据后缀为 .nii.gz).

**Comment by MR-HOLO** [comment]
抱歉,再次打扰了，我用你给我之前的OAI-ZIB的数据官网，它需要注册，我也发了邮件，但是还没回复我，现在还无法下载.nii格式的数据，这种情况我是继续等还是寻求其他方式，感谢。

**Comment by qinliuliuqin** [comment]
OAI-ZIB官网只提供分割mask，你还需要下载OAI数据集 (OAI-ZIB是OAI的子集)。
我把论文中用到的50例OAI-ZIB测试数据上传到 [Google Drive](https://drive.google.com/drive/folders/1Z8rklO1qP4vb7q-g3yTx7jADoxx5C0JO?usp=sharing)了。

**Comment by MR-HOLO** [comment]
很感谢你的帮助，已经顺利跑通

**Comment by MR-HOLO** [comment]
请问:
1.&nbsp;clicks encoding的代码部分
2. 训练和推理过程中，是如何做到自动模拟点击的
3. 2D切片传播到3D分割的过程是用的测试集的分割结果传播的吗
4. 我也想深入交互分割这个方向，请给一些基础的指导
感谢

**Comment by MR-HOLO** [comment]
收到你的回复，你有时间再看即可，我正在研究一些相关的论文和代码
之前的问题:
1. clicks encoding的代码细节和你的论文有些许不同(在输入到patch Embedding前clicks encoding 的cha=3)
2. 交互在训练过程中进行吗
3. 训练和推理过程中，是如何做到自动模拟点击的
4. 2D切片传播到3D分割的过程是用的测试集的分割结果传播的吗
5. 论文中3D的分割结果是如何可视化的(有什么好的可视化工具推荐)
感谢你的帮助

**Comment by MR-HOLO** [comment]
1. 传播模块是否是代替了预测集的作用(相当于没有测试集)
2. 交互软件是如何发挥它的作用,如何将训练和传播有机的结合在一起。
感谢你的回答

**Comment by qinliuliuqin** [comment]
>

**Comment by qinliuliuqin** [comment]
> 1. 传播模块是否是代替了预测集的作用(相当于没有测试集) 2. 交互软件是如何发挥它的作用,如何将训练和传播有机的结合在一起。 感谢你的回答 Message ID: ***@***.***&gt;

1. 我不是太理解这句话的意思。iSegFormer包含一个2D interactive segmentation (iSeg) 模块和一个传播分割模块，这两个模块是分开训练的。传播模块用的是[STCN](https://arxiv.org/pdf/2106.05210.pdf)，其作用是基于memory bank (即已经分割的帧)，获得query image (即待分割帧) 的分割结果。这有点类似few-shot learning，memory bank可以看作support set。 
2. 目前我们只提供了2D iSeg的交互工具 (基于[RITM](https://github.com/saic-vul/ritm_interactive_segmentation))，不包含传播模块 (未来会提供，参考STCN)。2D iSeg和传播模块是分开训练的，测试阶段只需要按照简单的传播规则就可以将二者结合在一起 (参考sec 3.3 of [MiVOS](https://arxiv.org/pdf/2103.07941.pdf))。

**Comment by qinliuliuqin** [comment]
交互工具直接基于[RITM](https://github.com/saic-vul/ritm_interactive_segmentation)。一般流程就是加载数据->点击分割->保存mask。如果你想标记一幅图里的多个object，那么每次标记完一个object之后点击Finish object，然后再标记新的object。交互界面上有一些参数设置可以直接使用默认值。

**Comment by MR-HOLO** [comment]
我想问下你在传播前的切片分割有dice 和 iou吗

**Comment by MR-HOLO** [comment]
我想问下你在传播前的切片分割有dice 和 iou吗?
如果有请发我一下，还有RITM分割的 dice 和 iou 十分感谢

**Comment by qinliuliuqin** [comment]
Hi, 我们直接用切片的金标准进行传播，得到3D的分割结果。理论上，我们可以使用交互工具得到非常接近金标准的切片分割结果。

**Comment by MR-HOLO** [comment]
你好，我想引用你的2D切片数据集作为我论文研究的数据对象并且引用你的论文是否可以。

**Comment by qinliuliuqin** [comment]
> 你好，我想引用你的2D切片数据集作为我论文研究的数据对象并且引用你的论文是否可以。

当然可以。2D切片数据集已经上传至 [https://github.com/qinliuliuqin/iSegFormer/releases/tag/v0.1](https://github.com/qinliuliuqin/iSegFormer/releases/tag/v0.1)
