### ISSUE TITLE
Training for propagate module

### ISSUE THREAD

**Issue by tony71200** [qinliuliuqin/iSegFormer#2]
Hi. I am researching interactive segmentation.
I read your paper about iSegformer and I'm really excited about this model. However I am having some problems training the propagation model on anaconda.
Could you please show me the command line to train a propagation model with 1 GPU?
Thank you very much and look forward to hearing from you.

**Comment by qinliuliuqin** [comment]
Thanks for your interest.
We don't train the propagation model in iSegFormer. Instead, we simply use the pretrained [STCN model](https://github.com/hkchengrex/STCN). Please refer to the STCN repository for [training instructions](https://github.com/hkchengrex/STCN#training).

**Comment by tony71200** [comment]
Thank you 👍🏼
